classDiagram

namespace guitool {
  class TabTemplate
}

namespace hexgui {
  class Model
  class SignalApplicationStatus
  class SignalControl
  class SignalPosition
  class SignalPower
}

Model *-- SignalApplicationStatus : emit()
Model *-- SignalControl : emit()
Model *-- SignalPosition : emit()
Model *-- SignalPower : emit()

TabTemplate <|-- TabTelemetry

TabTelemetry *-- Model
TabTelemetry --> SignalApplicationStatus : connect()
TabTelemetry --> SignalControl : connect()
TabTelemetry --> SignalPosition : connect()
TabTelemetry --> SignalPower : connect()
