classDiagram

namespace guitool {
  class TabTemplate
}

namespace hexgui {
  class Model
  class SignalPosition
}

Model *-- SignalPosition : emit()

TabTemplate <|-- TabPosition

TabPosition *-- Model
TabPosition --> SignalPosition : connect()
